name: Deploy Discord Overlays

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd discord-bot
        npm ci
    
    # Option 1: Deploy to Railway
    - name: Deploy to Railway
      if: env.RAILWAY_TOKEN != ''
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        npm install -g @railway/cli
        railway up
    
    # Option 2: Deploy to Heroku
    - name: Deploy to Heroku
      if: env.HEROKU_API_KEY != ''
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        cd discord-bot
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        heroku git:remote -a $HEROKU_APP_NAME
        git push heroku main
    
    # Option 3: Deploy static overlays to GitHub Pages
    - name: Deploy overlays to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./discord-bot/overlays
        cname: overlays.yourdomain.com # Optional: your custom domain
        
    # Option 4: Upload to S3 / CDN
    - name: Upload to AWS S3
      if: env.AWS_ACCESS_KEY_ID != ''
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        S3_BUCKET: your-bucket-name
      run: |
        aws s3 sync ./discord-bot/overlays s3://$S3_BUCKET/overlays --delete
        
    - name: Send notification
      if: success()
      run: |
        echo "Deployment successful! 🎉"
        # Add Discord webhook notification here if desired
        # curl -X POST -H 'Content-Type: application/json' \
        #   -d '{"content":"Overlays deployed successfully!"}' \
        #   ${{ secrets.DISCORD_WEBHOOK_URL }}